# Generated by Django 4.1.3 on 2022-11-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
