# Generated by Django 4.1.3 on 2022-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0002_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13-digit ISBN', max_length=20, unique=True, verbose_name='ISBN'),
        ),
    ]
